package net.adashofcolor.mod.content;

import net.adashofcolor.mod.blocks.Wood.*;
import net.minecraft.block.PressurePlateBlock;

public class CPlank {

    public static CPlankBlock BLEACHED_PLANKS;
    public static CPlankBlock BLACK_PLANKS;
    public static CPlankBlock BLUE_PLANKS;
    public static CPlankBlock BROWN_PLANKS;
    public static CPlankBlock CYAN_PLANKS;
    public static CPlankBlock GRAY_PLANKS;
    public static CPlankBlock GREEN_PLANKS;
    public static CPlankBlock LIGHT_BLUE_PLANKS;
    public static CPlankBlock LIGHT_GRAY_PLANKS;
    public static CPlankBlock LIME_PLANKS;
    public static CPlankBlock MAGENTA_PLANKS;
    public static CPlankBlock ORANGE_PLANKS;
    public static CPlankBlock PINK_PLANKS;
    public static CPlankBlock PURPLE_PLANKS;
    public static CPlankBlock RED_PLANKS;
    public static CPlankBlock WHITE_PLANKS;
    public static CPlankBlock YELLOW_PLANKS;

    public static CPlankStairs BLEACHED_PLANK_STAIRS;
    public static CPlankStairs BLACK_PLANK_STAIRS;
    public static CPlankStairs BLUE_PLANK_STAIRS;
    public static CPlankStairs BROWN_PLANK_STAIRS;
    public static CPlankStairs CYAN_PLANK_STAIRS;
    public static CPlankStairs GRAY_PLANK_STAIRS;
    public static CPlankStairs GREEN_PLANK_STAIRS;
    public static CPlankStairs LIGHT_BLUE_PLANK_STAIRS;
    public static CPlankStairs LIGHT_GRAY_PLANK_STAIRS;
    public static CPlankStairs LIME_PLANK_STAIRS;
    public static CPlankStairs MAGENTA_PLANK_STAIRS;
    public static CPlankStairs ORANGE_PLANK_STAIRS;
    public static CPlankStairs PINK_PLANK_STAIRS;
    public static CPlankStairs PURPLE_PLANK_STAIRS;
    public static CPlankStairs RED_PLANK_STAIRS;
    public static CPlankStairs WHITE_PLANK_STAIRS;
    public static CPlankStairs YELLOW_PLANK_STAIRS;

    public static CPlankSlab BLEACHED_PLANK_SLAB;
    public static CPlankSlab BLACK_PLANK_SLAB;
    public static CPlankSlab BLUE_PLANK_SLAB;
    public static CPlankSlab BROWN_PLANK_SLAB;
    public static CPlankSlab CYAN_PLANK_SLAB;
    public static CPlankSlab GRAY_PLANK_SLAB;
    public static CPlankSlab GREEN_PLANK_SLAB;
    public static CPlankSlab LIGHT_BLUE_PLANK_SLAB;
    public static CPlankSlab LIGHT_GRAY_PLANK_SLAB;
    public static CPlankSlab LIME_PLANK_SLAB;
    public static CPlankSlab MAGENTA_PLANK_SLAB;
    public static CPlankSlab ORANGE_PLANK_SLAB;
    public static CPlankSlab PINK_PLANK_SLAB;
    public static CPlankSlab PURPLE_PLANK_SLAB;
    public static CPlankSlab RED_PLANK_SLAB;
    public static CPlankSlab WHITE_PLANK_SLAB;
    public static CPlankSlab YELLOW_PLANK_SLAB;

    public static CPlankFence BLEACHED_PLANK_FENCE;
    public static CPlankFence BLACK_PLANK_FENCE;
    public static CPlankFence BLUE_PLANK_FENCE;
    public static CPlankFence BROWN_PLANK_FENCE;
    public static CPlankFence CYAN_PLANK_FENCE;
    public static CPlankFence GRAY_PLANK_FENCE;
    public static CPlankFence GREEN_PLANK_FENCE;
    public static CPlankFence LIGHT_BLUE_PLANK_FENCE;
    public static CPlankFence LIGHT_GRAY_PLANK_FENCE;
    public static CPlankFence LIME_PLANK_FENCE;
    public static CPlankFence MAGENTA_PLANK_FENCE;
    public static CPlankFence ORANGE_PLANK_FENCE;
    public static CPlankFence PINK_PLANK_FENCE;
    public static CPlankFence PURPLE_PLANK_FENCE;
    public static CPlankFence RED_PLANK_FENCE;
    public static CPlankFence WHITE_PLANK_FENCE;
    public static CPlankFence YELLOW_PLANK_FENCE;

    public static CPlankFenceGate BLEACHED_PLANK_FENCE_GATE;
    public static CPlankFenceGate BLACK_PLANK_FENCE_GATE;
    public static CPlankFenceGate BLUE_PLANK_FENCE_GATE;
    public static CPlankFenceGate BROWN_PLANK_FENCE_GATE;
    public static CPlankFenceGate CYAN_PLANK_FENCE_GATE;
    public static CPlankFenceGate GRAY_PLANK_FENCE_GATE;
    public static CPlankFenceGate GREEN_PLANK_FENCE_GATE;
    public static CPlankFenceGate LIGHT_BLUE_PLANK_FENCE_GATE;
    public static CPlankFenceGate LIGHT_GRAY_PLANK_FENCE_GATE;
    public static CPlankFenceGate LIME_PLANK_FENCE_GATE;
    public static CPlankFenceGate MAGENTA_PLANK_FENCE_GATE;
    public static CPlankFenceGate ORANGE_PLANK_FENCE_GATE;
    public static CPlankFenceGate PINK_PLANK_FENCE_GATE;
    public static CPlankFenceGate PURPLE_PLANK_FENCE_GATE;
    public static CPlankFenceGate RED_PLANK_FENCE_GATE;
    public static CPlankFenceGate WHITE_PLANK_FENCE_GATE;
    public static CPlankFenceGate YELLOW_PLANK_FENCE_GATE;

    public static CPlankButton BLEACHED_PLANK_BUTTON;
    public static CPlankButton BLACK_PLANK_BUTTON;
    public static CPlankButton BLUE_PLANK_BUTTON;
    public static CPlankButton BROWN_PLANK_BUTTON;
    public static CPlankButton CYAN_PLANK_BUTTON;
    public static CPlankButton GRAY_PLANK_BUTTON;
    public static CPlankButton GREEN_PLANK_BUTTON;
    public static CPlankButton LIGHT_BLUE_PLANK_BUTTON;
    public static CPlankButton LIGHT_GRAY_PLANK_BUTTON;
    public static CPlankButton LIME_PLANK_BUTTON;
    public static CPlankButton MAGENTA_PLANK_BUTTON;
    public static CPlankButton ORANGE_PLANK_BUTTON;
    public static CPlankButton PINK_PLANK_BUTTON;
    public static CPlankButton PURPLE_PLANK_BUTTON;
    public static CPlankButton RED_PLANK_BUTTON;
    public static CPlankButton WHITE_PLANK_BUTTON;
    public static CPlankButton YELLOW_PLANK_BUTTON;

    public static CPlankPressurePlate BLEACHED_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate BLACK_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate BLUE_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate BROWN_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate CYAN_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate GRAY_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate GREEN_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate LIGHT_BLUE_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate LIGHT_GRAY_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate LIME_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate MAGENTA_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate ORANGE_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate PINK_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate PURPLE_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate RED_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate WHITE_PLANK_PRESSURE_PLATE;
    public static CPlankPressurePlate YELLOW_PLANK_PRESSURE_PLATE;

    public static void init() {
        BLEACHED_PLANKS = new CPlankBlock("bleached_planks", 2.0f, 15.0f);
        BLACK_PLANKS = new CPlankBlock("black_planks", 2.0f, 15.0f);
        BLUE_PLANKS = new CPlankBlock("blue_planks", 2.0f, 15.0f);
        BROWN_PLANKS = new CPlankBlock("brown_planks", 2.0f, 15.0f);
        CYAN_PLANKS = new CPlankBlock("cyan_planks", 2.0f, 15.0f);
        GRAY_PLANKS = new CPlankBlock("gray_planks", 2.0f, 15.0f);
        GREEN_PLANKS = new CPlankBlock("green_planks", 2.0f, 15.0f);
        LIGHT_BLUE_PLANKS = new CPlankBlock("light_blue_planks", 2.0f, 15.0f);
        LIGHT_GRAY_PLANKS = new CPlankBlock("light_gray_planks", 2.0f, 15.0f);
        LIME_PLANKS = new CPlankBlock("lime_planks", 2.0f, 15.0f);
        MAGENTA_PLANKS = new CPlankBlock("magenta_planks", 2.0f, 15.0f);
        ORANGE_PLANKS = new CPlankBlock("orange_planks", 2.0f, 15.0f);
        PINK_PLANKS = new CPlankBlock("pink_planks", 2.0f, 15.0f);
        PURPLE_PLANKS = new CPlankBlock("purple_planks", 2.0f, 15.0f);
        RED_PLANKS = new CPlankBlock("red_planks", 2.0f, 15.0f);
        WHITE_PLANKS = new CPlankBlock("white_planks", 2.0f, 15.0f);
        YELLOW_PLANKS = new CPlankBlock("yellow_planks", 2.0f, 15.0f);

        BLEACHED_PLANK_STAIRS = new CPlankStairs(BLEACHED_PLANKS, "bleached_plank_stairs", 2.0f, 15.0f);
        BLACK_PLANK_STAIRS = new CPlankStairs(BLACK_PLANKS, "black_plank_stairs", 2.0f, 15.0f);
        BLUE_PLANK_STAIRS = new CPlankStairs(BLUE_PLANKS,"blue_plank_stairs", 2.0f, 15.0f);
        BROWN_PLANK_STAIRS = new CPlankStairs(BROWN_PLANKS,"brown_plank_stairs", 2.0f, 15.0f);
        CYAN_PLANK_STAIRS = new CPlankStairs(CYAN_PLANKS,"cyan_plank_stairs", 2.0f, 15.0f);
        GRAY_PLANK_STAIRS = new CPlankStairs(GRAY_PLANKS,"gray_plank_stairs", 2.0f, 15.0f);
        GREEN_PLANK_STAIRS = new CPlankStairs(GREEN_PLANKS,"green_plank_stairs", 2.0f, 15.0f);
        LIGHT_BLUE_PLANK_STAIRS = new CPlankStairs(LIGHT_BLUE_PLANKS,"light_blue_plank_stairs", 2.0f, 15.0f);
        LIGHT_GRAY_PLANK_STAIRS = new CPlankStairs(LIGHT_GRAY_PLANKS,"light_gray_plank_stairs", 2.0f, 15.0f);
        LIME_PLANK_STAIRS = new CPlankStairs(LIME_PLANKS,"lime_plank_stairs", 2.0f, 15.0f);
        MAGENTA_PLANK_STAIRS = new CPlankStairs(MAGENTA_PLANKS,"magenta_plank_stairs", 2.0f, 15.0f);
        ORANGE_PLANK_STAIRS = new CPlankStairs(ORANGE_PLANKS,"orange_plank_stairs", 2.0f, 15.0f);
        PINK_PLANK_STAIRS = new CPlankStairs(PINK_PLANKS,"pink_plank_stairs", 2.0f, 15.0f);
        PURPLE_PLANK_STAIRS = new CPlankStairs(PURPLE_PLANKS,"purple_plank_stairs", 2.0f, 15.0f);
        RED_PLANK_STAIRS = new CPlankStairs(RED_PLANKS,"red_plank_stairs", 2.0f, 15.0f);
        WHITE_PLANK_STAIRS = new CPlankStairs(WHITE_PLANKS,"white_plank_stairs", 2.0f, 15.0f);
        YELLOW_PLANK_STAIRS = new CPlankStairs(YELLOW_PLANKS,"yellow_plank_stairs", 2.0f, 15.0f);

        BLEACHED_PLANK_SLAB = new CPlankSlab("bleached_plank_slab", 2.0f, 15.0f);
        BLACK_PLANK_SLAB = new CPlankSlab("black_plank_slab", 2.0f, 15.0f);
        BLUE_PLANK_SLAB = new CPlankSlab("blue_plank_slab", 2.0f, 15.0f);
        BROWN_PLANK_SLAB = new CPlankSlab("brown_plank_slab", 2.0f, 15.0f);
        CYAN_PLANK_SLAB = new CPlankSlab("cyan_plank_slab", 2.0f, 15.0f);
        GRAY_PLANK_SLAB = new CPlankSlab("gray_plank_slab", 2.0f, 15.0f);
        GREEN_PLANK_SLAB = new CPlankSlab("green_plank_slab", 2.0f, 15.0f);
        LIGHT_BLUE_PLANK_SLAB = new CPlankSlab("light_blue_plank_slab", 2.0f, 15.0f);
        LIGHT_GRAY_PLANK_SLAB = new CPlankSlab("light_gray_plank_slab", 2.0f, 15.0f);
        LIME_PLANK_SLAB = new CPlankSlab("lime_plank_slab", 2.0f, 15.0f);
        MAGENTA_PLANK_SLAB = new CPlankSlab("magenta_plank_slab", 2.0f, 15.0f);
        ORANGE_PLANK_SLAB = new CPlankSlab("orange_plank_slab", 2.0f, 15.0f);
        PINK_PLANK_SLAB = new CPlankSlab("pink_plank_slab", 2.0f, 15.0f);
        PURPLE_PLANK_SLAB = new CPlankSlab("purple_plank_slab", 2.0f, 15.0f);
        RED_PLANK_SLAB = new CPlankSlab("red_plank_slab", 2.0f, 15.0f);
        WHITE_PLANK_SLAB = new CPlankSlab("white_plank_slab", 2.0f, 15.0f);
        YELLOW_PLANK_SLAB = new CPlankSlab("yellow_plank_slab", 2.0f, 15.0f);

        BLEACHED_PLANK_FENCE = new CPlankFence("bleached_plank_fence", 2.0f, 15.0f);
        BLACK_PLANK_FENCE = new CPlankFence("black_plank_fence", 2.0f, 15.0f);
        BLUE_PLANK_FENCE = new CPlankFence("blue_plank_fence", 2.0f, 15.0f);
        BROWN_PLANK_FENCE = new CPlankFence("brown_plank_fence", 2.0f, 15.0f);
        CYAN_PLANK_FENCE = new CPlankFence("cyan_plank_fence", 2.0f, 15.0f);
        GRAY_PLANK_FENCE = new CPlankFence("gray_plank_fence", 2.0f, 15.0f);
        GREEN_PLANK_FENCE = new CPlankFence("green_plank_fence", 2.0f, 15.0f);
        LIGHT_BLUE_PLANK_FENCE = new CPlankFence("light_blue_plank_fence", 2.0f, 15.0f);
        LIGHT_GRAY_PLANK_FENCE = new CPlankFence("light_gray_plank_fence", 2.0f, 15.0f);
        LIME_PLANK_FENCE = new CPlankFence("lime_plank_fence", 2.0f, 15.0f);
        MAGENTA_PLANK_FENCE = new CPlankFence("magenta_plank_fence", 2.0f, 15.0f);
        ORANGE_PLANK_FENCE = new CPlankFence("orange_plank_fence", 2.0f, 15.0f);
        PINK_PLANK_FENCE = new CPlankFence("pink_plank_fence", 2.0f, 15.0f);
        PURPLE_PLANK_FENCE = new CPlankFence("purple_plank_fence", 2.0f, 15.0f);
        RED_PLANK_FENCE = new CPlankFence("red_plank_fence", 2.0f, 15.0f);
        WHITE_PLANK_FENCE = new CPlankFence("white_plank_fence", 2.0f, 15.0f);
        YELLOW_PLANK_FENCE = new CPlankFence("yellow_plank_fence", 2.0f, 15.0f);

        BLEACHED_PLANK_FENCE_GATE = new CPlankFenceGate("bleached_plank_fence_gate", 2.0f, 15.0f);
        BLACK_PLANK_FENCE_GATE = new CPlankFenceGate("black_plank_fence_gate", 2.0f, 15.0f);
        BLUE_PLANK_FENCE_GATE = new CPlankFenceGate("blue_plank_fence_gate", 2.0f, 15.0f);
        BROWN_PLANK_FENCE_GATE = new CPlankFenceGate("brown_plank_fence_gate", 2.0f, 15.0f);
        CYAN_PLANK_FENCE_GATE = new CPlankFenceGate("cyan_plank_fence_gate", 2.0f, 15.0f);
        GRAY_PLANK_FENCE_GATE = new CPlankFenceGate("gray_plank_fence_gate", 2.0f, 15.0f);
        GREEN_PLANK_FENCE_GATE = new CPlankFenceGate("green_plank_fence_gate", 2.0f, 15.0f);
        LIGHT_BLUE_PLANK_FENCE_GATE = new CPlankFenceGate("light_blue_plank_fence_gate", 2.0f, 15.0f);
        LIGHT_GRAY_PLANK_FENCE_GATE = new CPlankFenceGate("light_gray_plank_fence_gate", 2.0f, 15.0f);
        LIME_PLANK_FENCE_GATE = new CPlankFenceGate("lime_plank_fence_gate", 2.0f, 15.0f);
        MAGENTA_PLANK_FENCE_GATE = new CPlankFenceGate("magenta_plank_fence_gate", 2.0f, 15.0f);
        ORANGE_PLANK_FENCE_GATE = new CPlankFenceGate("orange_plank_fence_gate", 2.0f, 15.0f);
        PINK_PLANK_FENCE_GATE = new CPlankFenceGate("pink_plank_fence_gate", 2.0f, 15.0f);
        PURPLE_PLANK_FENCE_GATE = new CPlankFenceGate("purple_plank_fence_gate", 2.0f, 15.0f);
        RED_PLANK_FENCE_GATE = new CPlankFenceGate("red_plank_fence_gate", 2.0f, 15.0f);
        WHITE_PLANK_FENCE_GATE = new CPlankFenceGate("white_plank_fence_gate", 2.0f, 15.0f);
        YELLOW_PLANK_FENCE_GATE = new CPlankFenceGate("yellow_plank_fence_gate", 2.0f, 15.0f);

        BLEACHED_PLANK_BUTTON = new CPlankButton("bleached_plank_button", 2.0f, 15.0f);
        BLACK_PLANK_BUTTON = new CPlankButton("black_plank_button", 2.0f, 15.0f);
        BLUE_PLANK_BUTTON = new CPlankButton("blue_plank_button", 2.0f, 15.0f);
        BROWN_PLANK_BUTTON = new CPlankButton("brown_plank_button", 2.0f, 15.0f);
        CYAN_PLANK_BUTTON = new CPlankButton("cyan_plank_button", 2.0f, 15.0f);
        GRAY_PLANK_BUTTON = new CPlankButton("gray_plank_button", 2.0f, 15.0f);
        GREEN_PLANK_BUTTON = new CPlankButton("green_plank_button", 2.0f, 15.0f);
        LIGHT_BLUE_PLANK_BUTTON = new CPlankButton("light_blue_plank_button", 2.0f, 15.0f);
        LIGHT_GRAY_PLANK_BUTTON = new CPlankButton("light_gray_plank_button", 2.0f, 15.0f);
        LIME_PLANK_BUTTON = new CPlankButton("lime_plank_button", 2.0f, 15.0f);
        MAGENTA_PLANK_BUTTON = new CPlankButton("magenta_plank_button", 2.0f, 15.0f);
        ORANGE_PLANK_BUTTON = new CPlankButton("orange_plank_button", 2.0f, 15.0f);
        PINK_PLANK_BUTTON = new CPlankButton("pink_plank_button", 2.0f, 15.0f);
        PURPLE_PLANK_BUTTON = new CPlankButton("purple_plank_button", 2.0f, 15.0f);
        RED_PLANK_BUTTON = new CPlankButton("red_plank_button", 2.0f, 15.0f);
        WHITE_PLANK_BUTTON = new CPlankButton("white_plank_button", 2.0f, 15.0f);
        YELLOW_PLANK_BUTTON = new CPlankButton("yellow_plank_button", 2.0f, 15.0f);

        BLEACHED_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("bleached_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        BLACK_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("black_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        BLUE_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("blue_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        BROWN_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("brown_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        CYAN_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("cyan_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        GRAY_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("gray_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        GREEN_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("green_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        LIGHT_BLUE_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("light_blue_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        LIGHT_GRAY_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("light_gray_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        LIME_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("lime_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        MAGENTA_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("magenta_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        ORANGE_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("orange_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        PINK_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("pink_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        PURPLE_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("purple_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        RED_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("red_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        WHITE_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("white_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);
        YELLOW_PLANK_PRESSURE_PLATE = new CPlankPressurePlate("yellow_plank_pressure_plate", 2.0f, 15.0f, PressurePlateBlock.ActivationRule.EVERYTHING);

    }
}